# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_ESPRESSIF) += esp32s31_generic.dtb
dtb-$(CONFIG_ARCH_ESPRESSIF) += esp32s31_korvo1.dtb
dtb-$(CONFIG_ARCH_ESPRESSIF) += esp32s31_function_coreboard_1.dtb
